### ISSUE TITLE
Tweak doesn't work anymore :(( 

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YTReExplore#1]
I just update Youtube latest version (16.45.4) and this tweak doesn't replace "Shorts tab" with "Explore tab" anymore.
Hope you can fix this issue, thank you for this useful tweak ;))

**Comment by PoomSmart** [comment]
1.0.2 fixes it.

**Comment by NguyenASang** [comment]
So fastttt =)))
Also check my question in uYouCompat repository.
