### ISSUE TITLE
Please consider supporting v16.20.5

### ISSUE THREAD

**Issue by hero3210** [PoomSmart/YTReExplore#2]
Thanks for making the much needed YTReExplore. 

Please consider supporting v16.20.5 as it is currently the latest version that supports [iSponsorBlock segment colors](https://github.com/Galactic-Dev/iSponsorBlock/issues/35).

Thanks again for all your efforts & contributions. You are truly inspiring with all your hard work and neat tweaking skills.

**Comment by PoomSmart** [comment]
This tweak works just fine on that version based on my testing.

**Comment by hero3210** [comment]
> This tweak works just fine on that version based on my testing.

You are right.. it worked after I upgraded to the latest version then downgraded back to 16.20.5

i guess there was some cache involved or something. 

Sorry about the false-alarm. Thanks again for all your hard work.
