### ISSUE TITLE
iPad support for YTReExplore

### ISSUE THREAD

**Issue by arichornlover** [PoomSmart/YTReExplore#3]
Recently YouTube added the Shorts tab to the iPad version of YouTube, today I came on the app and saw it. So I used your tweak to disable it but the results was this
![8E22CA62-474E-4BCE-A432-4BA1B3474A71](https://user-images.githubusercontent.com/78001398/178368187-006fed5d-6110-4873-965a-a394975cd10b.jpeg)
I know it isn’t a big deal but it shows 2 explore tabs on the app
Currently effects YouTube 16.42.3-17.26.2 or later versions

**Comment by PoomSmart** [comment]
Are you talking about one at the top left and the other at the tab bar?

**Comment by arichornlover** [comment]
Yep. YouTube must’ve changed something in the code and it does effect iPhones aswell. This change was recent and it might’ve been a server-side change

**Comment by PoomSmart** [comment]
But this tweak is meant to be installed on iPhones - replacing Shorts tab with Explore tab. On iPads, there's no such thing as "Shorts tab".

**Comment by arichornlover** [comment]
![D4CB6BCE-86BB-466C-9600-A02692B102FD](https://user-images.githubusercontent.com/78001398/178634603-a245c4ae-6bc8-4b78-8c3f-82ff3d98168e.jpeg)
But wait. Why do I have the tab then? it did show up on uYouPlus

**Comment by PoomSmart** [comment]
I'm talking about the tab bar at the bottom. Those at the top is not the scope of this tweak as it currently stands..

**Comment by arichornlover** [comment]
Oh, I guess I never knew about the second explore tab at the top when using this unique tweak
